## Input genome assembly files
Genomefna: testdata/GCF_000005845.2_ASM584v2_genomic.fna
Annotation: testdata/GCF_000005845.2_ASM584v2_feature_table.txt
List: testdata/GCF_000005845.2_ASM584v2.list
cds: testdata/GCF_000005845.2_ASM584v2_translated_cds.faa

## Parameters
Reference: bin/parameters/Bacteria.ref.dat
Length: 20
query_id: 60
query_cover: 50

## Tools: blastclust, cdhit, mmseqs
Tools: mmseqs
  #threshold for blastclust 
identity_b: 80 
coverage_b: 0.8
  #threshold for cdhit
identity_c: 0.8
coverage_c: 0.8
  #threshold for mmseqs: 
identity_m: 0.8
coverage_m: 0.8
covmode: 5
clustermode: 2 

## Enable Tritisa
Tritisa: True
